import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';
import {ProductStudio,productBrief} from '../../src/brain/product-studio.js';import {BrainStore} from '../../src/brain/store.js';import {Approvals} from '../../src/brain/approvals.js';import {ProductVideo,providerUrl,limitedBody} from '../../src/services/product-video.js';import {StudioCamera} from '../../dist/assets/studio-camera.js';import {workspaceKey} from '../../src/main/workspace-keys.js';import {workDurations,DURATIONS} from '../../src/state/machine.js';import {defaults,validateSettings} from '../../src/settings/schema.js';import {parseCommand} from '../../src/voice/commands.js';
const photo=Buffer.from('example-photo-bytes'),req=crypto.randomUUID(),origin='https://api.higgsfield.ai',storage='https://example.s3.amazonaws.com',mp4=Buffer.from('0000ftypisom0000');
function fixture(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'jarvis-studio-'));t.after(()=>{assert.ok(dir.startsWith(path.join(os.tmpdir(),'jarvis-studio-')));fs.rmSync(dir,{recursive:true,force:true});});const store=new BrainStore({dir,docs:dir,crypt:{available:()=>true,encrypt:s=>Buffer.from(s),decrypt:b=>b.toString()}});store.setSecret('higgsfieldKey','test-key:test-secret');const core={store,approvals:new Approvals({dir}),push(){},deps:{userDir:dir,normalisePhoto:async b=>b,openFile:async f=>f,mediaUrl:f=>'local:'+path.basename(f)}};const studio=new ProductStudio(core),calls=[];let price=.4,state='queued',failSubmit=false;
 core.studio=studio;studio.provider.fetch=async(url,o={})=>{calls.push({url,o});if(url.endsWith('generate-upload-url'))return Response.json({public_url:storage+'/photo.jpg',upload_url:storage+'/upload',upload_headers:{'Content-Type':'image/jpeg','x-amz-tagging':'temporary=true'}});if(url.endsWith('/upload'))return new Response(null,{status:200});if(url.includes('/estimate/'))return Response.json({usd:String(price)});if(url.endsWith('/image-to-video')){if(failSubmit)throw Error('Connection lost');return Response.json({request_id:req,status:state,status_url:origin+'/requests/'+req+'/status',cancel_url:origin+'/requests/'+req+'/cancel'});}if(url.endsWith('/status'))return Response.json({request_id:req,status:state,...(state==='completed'?{video:{url:storage+'/clip.mp4'}}:{})});if(url.endsWith('/clip.mp4'))return new Response(mp4);if(url.endsWith('/cancel'))return new Response(null,{status:202});throw Error('Unexpected request '+url);};return{dir,core,studio,calls,setPrice:x=>price=x,setState:x=>state=x,fail:()=>failSubmit=true};}
async function draft(f){const p=await f.studio.capture(photo);return f.studio.edit({...p,product:'Example bottle',scene:'Cold mist clears from a bottle standing on ice.',duration:5,maxCost:1});}
function approve(f,p){const {approval}=f.studio.request(p.id);const a=f.core.approvals.get(approval);f.core.approvals.decide(approval,true,{via:'ui'});return a.payload.input;}
test('draft photos and incomplete briefs remain local, persist and never need a provider key',async t=>{const f=fixture(t);f.core.store.setSecret('higgsfieldKey','');const p=await f.studio.capture(photo);f.studio.edit({...p,product:'Bottle',scene:''});assert.equal(f.calls.length,0);assert.equal(new ProductStudio(f.core).list().projects[0].product,'Bottle');assert.throws(()=>f.studio.request(p.id),/describe/);assert.throws(()=>productBrief({product:'x',scene:'a long enough scene',duration:5,maxCost:.001}),/estimate limit/);});
test('review is exact, deduplicated and invalidated by edited content',async t=>{const f=fixture(t),p=await draft(f),a=f.studio.request(p.id),b=f.studio.request(p.id);assert.equal(a.approval,b.approval);await assert.rejects(()=>f.studio.submit(f.core.approvals.get(a.approval).payload.input),/needs approval/);const input=approve(f,p);f.studio.edit({...p,scene:'Warm lights across a wooden table, with a bottle.'});await assert.rejects(()=>f.studio.submit(input),/changed/);assert.equal(f.calls.length,0);});
test('a changed reference picture cannot be uploaded under an old approval',async t=>{const f=fixture(t),p=await draft(f),input=approve(f,p);fs.writeFileSync(f.studio.photo(p),'replaced');await assert.rejects(()=>f.studio.submit(input),/changed/);assert.equal(f.calls.length,0);});
test('approved job uploads without exposing API auth to storage, reserves spend and downloads once',async t=>{const f=fixture(t),p=await draft(f);await f.studio.submit(approve(f,p));assert.equal(f.core.store.spent(),.4);const upload=f.calls.find(c=>c.o.method==='PUT');assert.equal(upload.o.headers.Authorization,undefined);assert.equal(upload.o.headers['x-amz-tagging'],'temporary=true');assert.match(f.calls[0].o.headers.Authorization,/^Key /);const submitted=f.calls.find(c=>c.url.endsWith('/image-to-video')&&!c.url.includes('/estimate/'));assert.equal(JSON.parse(submitted.o.body).image_url,storage+'/photo.jpg');assert.equal(JSON.parse(submitted.o.body).duration,5);f.setState('completed');const done=await f.studio.poll(p.id);assert.equal(done.job.state,'ready');assert.equal(done.job.statusUrl,undefined);assert.equal(done.job.outputUrl,undefined);assert.ok(fs.readFileSync(f.studio.fileFor(p,done.job.file)).equals(mp4));assert.equal(f.calls.at(-1).o.headers,undefined);const n=f.calls.length;await f.studio.poll(p.id);assert.equal(f.calls.length,n);});
test('expensive estimates stop before generation and do not reserve money',async t=>{const f=fixture(t),p=await draft(f);f.setPrice(1.5);await assert.rejects(()=>f.studio.submit(approve(f,p)),/exceeds/);assert.equal(f.core.store.spent(),0);assert.equal(f.calls.filter(c=>c.url===origin+'/kling-video/v2.5-turbo/pro/image-to-video').length,0);});
test('uncertain submissions keep reservation and never automatically resubmit after restart',async t=>{const f=fixture(t),p=await draft(f),input=approve(f,p);f.fail();await assert.rejects(()=>f.studio.submit(input),/uncertain/);assert.equal(f.core.store.spent(),.4);const restarted=new ProductStudio(f.core);assert.equal(restarted.get(p.id).job.state,'needs check');const n=f.calls.length;await restarted.tick();assert.equal(f.calls.length,n);assert.throws(()=>restarted.request(p.id),/already has/);});
test('queued requests resume by polling and cancellation is never sent for in-progress work',async t=>{const f=fixture(t),p=await draft(f);await f.studio.submit(approve(f,p));const restarted=new ProductStudio(f.core);restarted.provider=f.studio.provider;f.setState('in_progress');await restarted.poll(p.id);assert.equal(restarted.get(p.id).job.state,'in_progress');await assert.rejects(()=>restarted.cancel(p.id),/Only a queued/);f.setState('queued');await restarted.poll(p.id);assert.equal((await restarted.cancel(p.id)).job.state,'canceled');assert.equal(f.calls.filter(c=>c.o.method==='POST'&&c.url.endsWith('/cancel')).length,1);});
test('corrupt project stores and unsafe file paths cannot overwrite or open other files',async t=>{const f=fixture(t),p=await draft(f);assert.throws(()=>f.studio.fileFor(p,'../../secret.txt'),/Invalid/);fs.writeFileSync(f.studio.file,'not json');const s=new ProductStudio(f.core);await assert.rejects(()=>s.capture(photo),/preserved/);assert.equal(fs.readFileSync(s.file,'utf8'),'not json');});
test('provider addresses, bounded transfers and MP4 validation reject unsafe results',async()=>{for(const u of ['http://example.s3.amazonaws.com/x','https://evil.example/x','https://api.higgsfield.ai.evil.example/x','https://user:password@api.higgsfield.ai/x'])assert.throws(()=>providerUrl(u));assert.throws(()=>providerUrl(storage+'/x',true));await assert.rejects(()=>limitedBody(new Response('oversized'),2),/too large/);const v=new ProductVideo({key:()=>'',fetchImpl:async()=>new Response('<html>not a clip</html>')});await assert.rejects(()=>v.download(storage+'/x'),/not an MP4/);});
test('a late camera permission reply is stopped after closing the capture view',async()=>{let resolve,stops=0,constraints;const camera=new StudioCamera({getUserMedia:c=>{constraints=c;return new Promise(r=>resolve=r);}}),video={isConnected:true,play:async()=>{}};const pending=camera.start(video);camera.stop();resolve({getTracks:()=>[{stop:()=>stops++}]});assert.equal(await pending,false);assert.equal(stops,1);assert.equal(constraints.audio,false);assert.equal(video.srcObject,undefined);});
test('camera stops every track on capture close and also on preview failure',async()=>{let stops=0;const camera=new StudioCamera({getUserMedia:async()=>({getTracks:()=>[{stop:()=>stops++},{stop:()=>stops++}]})});await camera.start({isConnected:true,play:async()=>{}});camera.stop();assert.equal(stops,2);await assert.rejects(()=>camera.start({isConnected:true,play:async()=>{throw Error('preview failed');}}),/preview failed/);assert.equal(stops,4);});
test('browser shortcuts avoid plain typing, AltGr, IME and key-up',()=>{const key=k=>({type:'keyDown',control:true,key:k});assert.equal(workspaceKey(key('k')),'menu');assert.equal(workspaceKey({...key('t'),shift:true}),'reopen');assert.equal(workspaceKey({...key('Tab'),shift:true}),'previous');for(const patch of [{control:false},{alt:true},{isComposing:true},{type:'keyUp'},{shift:true}])assert.equal(workspaceKey({...key('k'),...patch}),null);});
test('quick work shortens only suit transitions and persists as a validated setting',()=>{const s=validateSettings({quickWork:true});const d=workDurations(s);assert.equal(d.SUIT_SELECTED,220);assert.equal(d.RETURNING,180);assert.equal(d.BOOT,workDurations(defaults).BOOT);assert.equal(workDurations({...defaults,startup:{enabled:false}}).SUIT_SELECTED,DURATIONS.SUIT_SELECTED);assert.throws(()=>validateSettings({quickWork:'yes'}));});
test('voice opens the studio without capturing, uploading or starting a paid job',()=>{assert.deepEqual(parseCommand('Jarvis open product studio',{theme:{assistant:'Jarvis'},themes:[],modules:[]}),{action:'product-studio'});assert.equal(parseCommand('open product studio',{theme:{assistant:'Jarvis'},themes:[],modules:[]}),null);});
