import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
import {writeJson,writeText} from './util.js';import {ProductVideo,VIDEO_MODEL,providerUrl} from '../services/product-video.js';
const text=(v,n=2000)=>String(v??'').trim().slice(0,n),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),ID=/^[a-f0-9-]{36}$/;
export function productBrief(p,{draft=false}={}){const product=text(p.product,160),scene=text(p.scene,1600);if(!draft&&(!product||scene.length<12))throw Error('Name the product and describe the scene in a sentence.');const duration=Number(p.duration);if(![5,10].includes(duration))throw Error('Choose a five or ten second clip.');const maxCost=Number(p.maxCost);if(!Number.isFinite(maxCost)||maxCost<.01||maxCost>20)throw Error('Choose an estimate limit between $0.01 and $20.');return {product,scene,duration,maxCost:Math.round(maxCost*100)/100,prompt:`Create a cinematic product shot of ${product}. ${scene}\nKeep the reference product’s shape, colours, proportions and existing label unchanged. Realistic materials and restrained camera movement. No new words, logos, people or unsupported product claims. Finish on a clean hero shot.`,model:VIDEO_MODEL};}
export class ProductStudio {
  constructor(core){this.core=core;this.file=path.join(core.deps.userDir,'product-studio.json');this.home=path.join(core.store.home,'Product Studio');this.projects=[];this.running=new Set();this.provider=new ProductVideo({key:()=>core.store.secret('higgsfieldKey'),fetchImpl:core.deps.fetch});try{if(fs.existsSync(this.file)){const d=JSON.parse(fs.readFileSync(this.file));if(!Array.isArray(d)||d.some(p=>!ID.test(p.id)))throw Error('Invalid projects');this.projects=d;for(const p of this.projects)if(['uploading','submitting'].includes(p.job?.state)){p.job.state='needs check';p.job.error='JARVIS stopped during submission. Check Higgsfield request history before making another request; it was not repeated.';}}}catch{this.error='Saved Product Studio projects could not be read. They have been preserved; restore a backup before saving.';}}
  save(){if(this.error)throw Error(this.error);writeJson(this.file,this.projects,2);}
  get(id){const p=this.projects.find(p=>p.id===id);if(!p)throw Error('Choose a saved product project.');return p;}
  fileFor(p,name){if(!ID.test(p.id)||typeof name!=='string'||/[\\/]/.test(name)||name==='..')throw Error('Invalid project file.');return path.join(this.home,p.id,name);}
  photo(p){return this.fileFor(p,'product.jpg');}
  public(p){return {...p,job:p.job?{...p.job,statusUrl:undefined,cancelUrl:undefined,outputUrl:undefined}:null,photoUrl:this.core.deps.mediaUrl?.(this.photo(p))||'',videoUrl:p.job?.state==='ready'?this.core.deps.mediaUrl?.(this.fileFor(p,p.job.file))||'':''};}
  list(){return {projects:this.projects.slice().reverse().map(p=>this.public(p)),ready:!!this.core.store.secret('higgsfieldKey'),error:this.error||'',model:VIDEO_MODEL};}
  async capture(bytes){if(this.error)throw Error(this.error);if(this.projects.length>=100)throw Error('Product Studio holds up to 100 projects. Export existing work before starting a new library.');if(!(bytes instanceof Uint8Array)||bytes.length>6*1024*1024||bytes.length<12)throw Error('Choose a JPEG or PNG photo below 6 MB.');const photo=await this.core.deps.normalisePhoto(Buffer.from(bytes)),p={id:crypto.randomUUID(),at:Date.now(),product:'',scene:'',duration:5,maxCost:1,photoHash:sha(photo),theme:this.core.deps.workstations?.activeTheme||'ironman',job:null};writeText(this.photo(p),photo);this.projects.push(p);this.save();return this.public(p);}
  edit(p){const old=this.get(p.id);if(this.running.has(old.id)||old.job&&!['ready','failed','nsfw','canceled'].includes(old.job.state))throw Error('Wait for the current request to finish submitting.');const brief=productBrief(p,{draft:true});Object.assign(old,brief,{updatedAt:Date.now()});this.save();return this.public(old);}
  digest(p){return sha(JSON.stringify({...productBrief(p),photoHash:p.photoHash}));}
  request(id){const p=this.get(id);productBrief(p);if(!this.core.store.secret('higgsfieldKey'))throw Error('Save your Higgsfield API credentials first. Drafts and camera capture work without them.');if(p.job&&!['failed','nsfw','canceled','ready'].includes(p.job.state))throw Error('This project already has a request. Check its progress or cancel it first.');const digest=this.digest(p),existing=this.core.approvals.list({status:'waiting'}).find(a=>a.payload?.tool==='product_render'&&a.payload.input?.id===id&&a.payload.input?.digest===digest);if(existing)return {approval:existing.id};const a=this.core.approvals.create({kind:'tool',risk:'high',title:'Start product clip: '+p.product,detail:`Send this saved product photo and scene to Higgsfield. Model: Kling 2.5 Turbo Pro; ${p.duration} seconds, silent.\n\n${p.prompt}\n\nCheck the live estimate before submitting: at most $${p.maxCost.toFixed(2)}. This is an estimate limit; Higgsfield controls the final charge. Also respects the remaining Core daily allowance. No automatic resubmission. Review the result before sharing; nothing is published.`,payload:{tool:'product_render',input:{id,digest}},source:'Product Studio'});this.core.push();return {approval:a.id};}
  async submit({id,digest}){const p=this.get(id);if(digest!==this.digest(p)||sha(fs.readFileSync(this.photo(p)))!==p.photoHash)throw Error('The product or brief changed after review. Request approval again.');const approval=this.core.approvals.list({limit:1000}).find(a=>a.status==='approved'&&a.payload?.tool==='product_render'&&a.payload.input?.id===id&&a.payload.input?.digest===digest);if(!approval)throw Error('This exact product request needs approval.');if(this.running.has(id)||p.job&&['uploading','submitting','queued','in_progress','needs check','downloading'].includes(p.job.state))throw Error('This request has already started.');this.running.add(id);p.job={id:crypto.randomUUID(),state:'uploading',at:Date.now(),duration:p.duration,prompt:p.prompt,digest,approval:approval.id};this.save();
    try{if(this.core.store.budgetLeft()<=0)throw Error('The daily AI allowance is used up.');const url=await this.provider.upload(fs.readFileSync(this.photo(p))),input=this.provider.input(p.job,url),estimate=await this.provider.estimate(input);if(estimate>p.maxCost||estimate>this.core.store.budgetLeft())throw Error(`The live estimate ($${estimate.toFixed(2)}) exceeds your allowed amount. No video was submitted.`);p.job.estimate=estimate;this.core.store.addSpend(estimate,'product video reservation');p.job.state='submitting';this.save();const r=await this.provider.submit(input);this.record(p,r);this.save();return 'Product clip submitted. Follow its progress in Product Studio.';}
    catch(e){p.job.state=p.job.state==='submitting'?'needs check':'failed';p.job.error=p.job.state==='needs check'?'Submission outcome is uncertain. Check Higgsfield request history before retrying. '+e.message:e.message;this.save();throw Error(p.job.error);}finally{this.running.delete(id);}}
  record(p,r){if(typeof r.request_id!=='string'||!ID.test(r.request_id))throw Error('Provider did not return a valid request ID.');p.job.requestId=r.request_id;p.job.statusUrl=providerUrl(r.status_url,true);if(!new URL(p.job.statusUrl).pathname.startsWith('/requests/'+r.request_id+'/'))throw Error('Unexpected status address.');p.job.cancelUrl=r.cancel_url?providerUrl(r.cancel_url,true):null;if(p.job.cancelUrl&&new URL(p.job.cancelUrl).pathname!=='/requests/'+r.request_id+'/cancel')throw Error('Unexpected cancellation address.');p.job.state=['queued','in_progress','completed','failed','nsfw','canceled'].includes(r.status)?r.status:'queued';p.job.nextCheck=Date.now()+10000;if(r.video?.url)p.job.outputUrl=providerUrl(r.video.url);}
  async poll(id){const p=this.get(id);if(this.running.has(id)||!p.job?.statusUrl||['ready','failed','nsfw','canceled'].includes(p.job.state))return this.public(p);this.running.add(id);try{const r=await this.provider.status(p.job.statusUrl);if(r.request_id&&r.request_id!==p.job.requestId)throw Error('Provider returned another request.');if(!['queued','in_progress','completed','failed','nsfw','canceled'].includes(r.status))throw Error('Unknown provider status.');p.job.state=r.status;delete p.job.error;p.job.nextCheck=Date.now()+(Date.now()-p.job.at>600000?120000:20000);
      if(r.status==='completed'){p.job.outputUrl=providerUrl(r.video?.url||p.job.outputUrl);p.job.state='downloading';this.save();const bytes=await this.provider.download(p.job.outputUrl),name='clip-'+p.job.id+'.mp4';writeText(this.fileFor(p,name),bytes);p.job.file=name;p.job.state='ready';p.job.finishedAt=Date.now();writeText(this.fileFor(p,'brief-'+p.job.id+'.md'),`# ${p.product}\n\n${p.job.prompt}\n\nModel: ${VIDEO_MODEL}\nDuration: ${p.job.duration}s\nReserved estimate: $${p.job.estimate}\nRequest: ${p.job.requestId}\n`);this.core.deps.notify?.('Product clip ready',p.product);}
      this.save();return this.public(p);
    }catch(e){p.job.error=e.message;p.job.nextCheck=Date.now()+60000;this.save();return this.public(p);}finally{this.running.delete(id);}}
  async cancel(id){const p=this.get(id);if(this.running.has(id))throw Error('A progress check is running. Try again in a moment.');if(p.job?.state!=='queued'||!p.job.cancelUrl)throw Error('Only a queued clip can be cancelled. A started generation cannot be cancelled.');this.running.add(id);try{await this.provider.cancel(p.job.cancelUrl);p.job.state='canceled';this.save();return this.public(p);}finally{this.running.delete(id);}}
  /** Checks every 20 seconds at first, then every 2 minutes; after a day without a result it stops and asks you to look. */
  async tick(){for(const p of this.projects)if(p.job?.statusUrl&&!['ready','failed','nsfw','canceled','needs check'].includes(p.job.state)){
    if(Date.now()-p.job.at>864e5){p.job.state='needs check';p.job.error='No finished clip after a day, so JARVIS has stopped checking. Look in your Higgsfield request history.';this.save();continue;}
    if(Date.now()>=(p.job.nextCheck||0))await this.poll(p.id);}}
  export(id){const p=this.get(id),brief=productBrief(p);writeText(this.fileFor(p,'Scene brief.md'),`# ${brief.product}\n\n${brief.prompt}\n\n${brief.duration} seconds. Review all labels and product details before sharing.\n`);return this.core.deps.openFile(this.fileFor(p,'Scene brief.md'));}
  open(id){const p=this.get(id);return this.core.deps.openFile(this.fileFor(p,p.job?.state==='ready'?p.job.file:''));}
}
