// ⚠ NOT LOADED AT RUNTIME. The settings UI that actually runs is the prebuilt
// renderer bundle in dist/assets/ (index-*.js). There is no build step that
// regenerates dist/ from this file, so edits here change NOTHING in the app.
// To change the settings UI you must patch dist/assets/index-*.js directly.
// Kept only as readable reference for the bundled code.
import {esc,bindForm} from '../utils/dom.js';
import {mountWorkstationSettings} from './workstations.js';
const tabs=['Workstations','General','Displays','Voice','Audio','Graphics','Services','System'];
const check=(key,label,value)=>`<label class="check"><input type="checkbox" name="${key}" ${value?'checked':''}>${label}</label>`;
const select=(name,label,options,value)=>`<label>${label}<select name="${name}">${options.map(([v,l])=>`<option value="${esc(v)}" ${String(value)===String(v)?'selected':''}>${esc(l)}</option>`).join('')}</select></label>`;
export function mountSettings(el,ctx){
  let tab='Workstations';el.innerHTML=`<main class="settings-shell"><aside><div class="brand"><b>J</b><span>JARVIS<small>WORKSPACE SETTINGS</small></span></div><nav>${tabs.map(t=>`<button data-tab="${t}">${t}</button>`).join('')}</nav><p class="small muted">ARMOR WORKSPACE<br>VERSION ${esc(ctx.version)}</p></aside><section class="settings-content"></section></main>`;el.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;draw();});
  let draw=async function(){
    el.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));const s=ctx.settings;let content='';
    if(tab==='General')content=`<p class="muted">Make JARVIS part of your daily rhythm.</p>${check('startWithWindows','Start with Windows',s.startWithWindows)}${check('startMinimized','Start minimized in the system tray',s.startMinimized)}${check('autoStart','Activate work mode automatically on launch',s.autoStart)}${check('wallpaper','Run animated desktop wallpaper',s.wallpaper)}${check('animations','Ambient motion and parallax',s.animations)}<h3>Keyboard shortcuts</h3><p class="small muted">Use Electron accelerators, for example Control+Alt+J.</p>${Object.entries(s.hotkeys).map(([k,v])=>`<label>${{wake:'Start work mode',home:'Armor hall',standdown:'Stand down',back:'Back (inside JARVIS)'}[k]}<input name="hotkey-${k}" value="${esc(v)}" required></label>`).join('')}<p class="small muted">The tray icon remains available so you can always reach Settings and Quit.</p>`;
    if(tab==='Displays'){const b=await ctx.api('bootstrap');ctx.displays=b.displays;const opts=ctx.displays.map(d=>[d.id,`${d.number} · ${d.label} · ${d.bounds.width}×${d.bounds.height}`]);content=`<p class="muted">Assign the top cinematic display and lower control deck.</p><div class="display-cards">${ctx.displays.map(d=>`<div><strong>${d.number}</strong><span>${esc(d.label)}</span><small>${d.bounds.width} × ${d.bounds.height} · Scale ${d.scaleFactor||1}</small></div>`).join('')}</div><button type="button" data-identify>Identify displays</button>${select('mainDisplay','Main cinematic display',[['','Automatic'],...opts],s.mainDisplay??'')}${select('controlDisplay','Control display',[['','Automatic'],...opts],s.controlDisplay??'')}<button type="button" data-swap>Swap assignments</button>${check('singleScreen','Use a single display',s.singleScreen)}<label>Interface scale<input name="scale" type="range" min="0.75" max="1.5" step="0.05" value="${s.scale}"></label><p class="small muted">Display resolution follows Windows automatically. Change physical resolution in Windows Display Settings.</p>`;}
    if(tab==='Voice')content=`<p class="muted">Offline Windows speech recognition uses your default microphone and an installed English recognizer.</p>${check('voiceEnabled','Enable microphone and voice commands',s.voiceEnabled)}<div class="status-box" style="white-space:pre-wrap">${esc(ctx.status.voice)}</div><pre class="small muted" data-voice-report hidden></pre><h3>Microphone level</h3><div class="mic-meter"><div class="mic-bar" data-mic-bar></div><span data-mic-text>Waiting for sound…</span></div><p class="small muted" data-mic-info>The bar should jump when you talk. If it stays flat, Windows is using the wrong microphone: use “Choose Windows microphone” below, pick your laptop mic as the default Input device, then turn voice off and on again.</p><h3>What Jarvis heard</h3><p class="small muted">Say a command now. Green = accepted and acted on, amber = heard but not a known command or wrong state, grey = too unclear (say it a little slower, normal volume).</p><div class="heard-list" data-heard></div><div class="button-row"><button type="button" data-microphone>Test microphone</button><button type="button" data-voice-check>Run voice check</button><button type="button" data-sound-settings>Choose Windows microphone</button></div><label>Installed Windows voice name (optional)<input name="voiceName" value="${esc(s.voiceName)}" placeholder="Leave blank to prefer an installed British English voice"></label><button type="button" data-audio>Test spoken response</button><p class="small muted">No actor voice is cloned. If a British English voice is not installed, Windows uses its available default voice. Microphone access can always be disabled.</p><p class="voice-phrase\">“${esc(ctx.theme.theme.assistant)}, let's get to work.” · “Jarvis, going dark.” · “Alfred, show Spider-Man.” · “Karen, bring Jarvis back.” · “${esc(ctx.theme.theme.assistant)}, open [suit name].”</p>`;
    if(tab==='Audio')content=`<p class="muted">Original synthesized sounds. Each channel has independent volume.</p>${['master','voice','interface','mechanical','ambience','music'].map(k=>`<label class="volume-label">${k.toUpperCase()} <output>${Math.round(s[k]*100)}%</output><input type="range" min="0" max="1" step="0.01" name="${k}" value="${s[k]}"></label>`).join('')}<button type="button" data-audio>Test audio</button><p class="small muted">Ambience is intentionally subtle. Audio failures leave navigation usable.</p><h3>Startup sequence</h3><p class="muted">When you say “${esc(ctx.theme.theme.assistant)}, let's get to work” (or press the hotkey), this video plays as the transition screen and this sound plays over it.</p>${check('startup-enabled','Play my startup video and sound',s.startup.enabled)}<div class="ws-folder-row"><code>${esc(s.startup.video?s.startup.video.split('/').pop():'No video')}</code><button type="button" data-startup-video>Choose video</button><button type="button" data-startup-video-clear>Remove</button></div><div class="ws-folder-row"><code>${esc(s.startup.sound?s.startup.sound.split('/').pop():'No sound')}</code><button type="button" data-startup-sound>Choose sound</button><button type="button" data-startup-sound-clear>Remove</button></div><label>Sequence length (seconds, matches your sound)<input name="startup-seconds" type="number" min="6" max="90" step="0.5" value="${s.startup.seconds}"></label>${check('startup-loop','Loop the video if it is shorter than the sequence',s.startup.loopVideo)}<p class="small muted">The startup sound follows the MUSIC channel volume.</p>`;
    if(tab==='Graphics')content=`<p class="muted">Quality adjusts render resolution, live floor reflections, shadows, bloom and particles.</p>${select('quality','Quality',['auto','low','medium','high','ultra'].map(x=>[x,x.toUpperCase()]),s.quality)}${select('fps','Frame rate',[[15,'Battery saver · 15 FPS'],[30,'30 FPS'],[60,'60 FPS']],s.fps)}${check('reduceOnBattery','Reduce graphics automatically on battery',s.reduceOnBattery)}<p class="small muted">Idle wallpaper renders at 10 FPS (5 on battery). Work mode drops to 15 FPS with lower resolution on battery. Medium is a good starting point for integrated graphics.</p>`;
    if(tab==='Services')content=`<h3>Weather</h3><p class="muted">Optional Open-Meteo connection. Coordinates are sent only when weather is enabled.</p>${check('weather-enabled','Enable weather',s.weather.enabled)}<div class="two-col"><label>Latitude<input name="latitude" type="number" step="any" min="-90" max="90" value="${s.weather.latitude??''}" placeholder="e.g. -26.18"></label><label>Longitude<input name="longitude" type="number" step="any" min="-180" max="180" value="${s.weather.longitude??''}" placeholder="e.g. 28.13"></label></div><h3>AI service</h3><p class="muted">Use an HTTPS chat-completions-compatible endpoint. Your key is encrypted with Windows credential protection.</p>${check('ai-enabled','Enable AI service',s.ai.enabled)}<label>Endpoint<input name="endpoint" type="url" value="${esc(s.ai.endpoint)}" placeholder="https://your-provider.example/v1/chat/completions"></label><label>Model identifier<input name="model" value="${esc(s.ai.model)}"></label><label>API key<input name="api-key" type="password" autocomplete="off" placeholder="Leave blank to keep existing key"></label><button type="button" data-key-delete>Delete saved key</button><h3>Calendar & email</h3><p class="muted">Calendar events are stored locally. Google Calendar and email synchronization are not connected. The default email shortcut opens your installed email app. See the integration guide in the source package.</p>`;
    if(tab==='System')content=`<p class="muted">Inspect current service status and recover settings.</p><div class="status-box">${esc(ctx.status.wallpaper)}</div><h3>Backup</h3><p class="muted">Saves your suits, folders, links, apps and preferences to a single file. Restoring keeps a rescue copy of whatever it replaces.</p><div class="button-row"><button type="button" data-backup-export>Export backup…</button><button type="button" data-backup-import>Restore from backup…</button></div><p class="small muted" data-backup-msg></p><h3>Updates</h3><div class="button-row"><button type="button" data-update-check>Check for updates</button></div><p class="small muted" data-update-msg>Version ${esc(ctx.version||"")}</p><h3>Diagnostics</h3><div class="button-row"><button type="button" data-diagnostics>Refresh diagnostics</button><button type="button" data-logs>Open log</button><button type="button" data-cache>Clear Chromium cache</button></div><pre class="diagnostic-output"></pre><button type="button" data-reset>Reset application settings…</button><p class="small muted">Reset keeps your local calendar and imported assets. Logs never include API keys.</p>`;
    const area=el.querySelector('.settings-content');if(tab==='Workstations'){mountWorkstationSettings(area,ctx);return;}area.innerHTML=`<div class="settings-heading"><p class="eyebrow">PREFERENCES / ${tab.toUpperCase()}</p><h1>${tab}.</h1></div><form>${content}${tab!=='System'?'<footer><button class="primary" type="submit">Save changes</button><span class="save-status"></span></footer>':''}</form>`;
    const form=area.querySelector('form');
    const call=(selector,method,payload)=>{const b=form.querySelector(selector);if(b)b.onclick=()=>ctx.api(method,payload).then(()=>ctx.notify('Done.')).catch(e=>ctx.notify(e.message));};
    call('[data-identify]','identify');call('[data-audio]','audio-test');call('[data-microphone]','microphone-test');call('[data-sound-settings]','system-microphone');call('[data-logs]','open-logs');call('[data-cache]','clear-cache');call('[data-reset]','reset-settings');call('[data-key-delete]','ai-key','');
    form.querySelector('[data-swap]')?.addEventListener('click',()=>{let a=form.elements.mainDisplay.value,b=form.elements.controlDisplay.value;if(!a)a=String(ctx.displays[0]?.id||'');if(!b)b=String(ctx.displays[1]?.id||'');form.elements.mainDisplay.value=b;form.elements.controlDisplay.value=a;});
    form.querySelectorAll('input[type=range]').forEach(input=>input.oninput=()=>{const output=input.parentElement.querySelector('output');if(output)output.textContent=Math.round(Number(input.value)*100)+'%';});
    for(const [sel,type,key]of [['[data-startup-video]','startup-video','video'],['[data-startup-sound]','startup-sound','sound']]){form.querySelector(sel)?.addEventListener('click',async()=>{try{const url=await ctx.api('choose',{type});if(typeof url==='string'){await ctx.save({startup:{...ctx.settings.startup,[key]:url}});draw();}}catch(e){ctx.notify(e.message);}});form.querySelector(sel.replace(']','-clear]'))?.addEventListener('click',()=>ctx.save({startup:{...ctx.settings.startup,[key]:''}}).then(draw).catch(e=>ctx.notify(e.message)));}
    const bmsg=(t)=>{const el=form.querySelector('[data-backup-msg]');if(el)el.textContent=t;};
    form.querySelector('[data-backup-export]')?.addEventListener('click',async()=>{bmsg('Saving…');try{const r=await ctx.api('backup-export');bmsg(r?.saved?('Backup saved to '+r.path):'Cancelled.');}catch(e){bmsg('Could not save: '+e.message);}});
    form.querySelector('[data-backup-import]')?.addEventListener('click',async()=>{bmsg('Restoring…');try{const r=await ctx.api('backup-import');bmsg(r?.restored?('Restored'+(r.savedAt?(' from '+new Date(r.savedAt).toLocaleString()):'')+'. Restart JARVIS to load it.'):'Cancelled.');}catch(e){bmsg('Could not restore: '+e.message);}});
    form.querySelector('[data-update-check]')?.addEventListener('click',async()=>{const el=form.querySelector('[data-update-msg]');if(el)el.textContent='Checking…';try{const r=await ctx.api('update-check');if(!el)return;el.textContent=r?.error?('Could not check: '+r.error):r.update?('Version '+r.latest+' is available (you have '+r.current+'). '+(r.url||'')):('You are up to date (version '+r.current+').');}catch(e){if(el)el.textContent='Could not check: '+e.message;}});
    form.querySelector('[data-voice-check]')?.addEventListener('click',async()=>{const pre=form.querySelector('[data-voice-report]');if(!pre)return;pre.hidden=false;pre.textContent='Checking Windows speech engines…';try{pre.textContent=JSON.stringify(await ctx.api('voice-diagnose'),null,2);}catch(e){pre.textContent=e.message;}});
    const diagnostics=async()=>{try{form.querySelector('pre').textContent=JSON.stringify(await ctx.api('diagnostics'),null,2);}catch(e){ctx.notify(e.message);}};form.querySelector('[data-diagnostics]')?.addEventListener('click',diagnostics);if(tab==='System')diagnostics();
    bindForm(form,async data=>{
      let patch={};
      if(tab==='General'){for(const k of ['startWithWindows','startMinimized','autoStart','wallpaper','animations'])patch[k]=data.has(k);patch.hotkeys=Object.fromEntries(Object.keys(s.hotkeys).map(k=>[k,data.get('hotkey-'+k)]));}
      if(tab==='Displays')patch={mainDisplay:data.get('mainDisplay')?Number(data.get('mainDisplay')):null,controlDisplay:data.get('controlDisplay')?Number(data.get('controlDisplay')):null,singleScreen:data.has('singleScreen'),scale:Number(data.get('scale'))};
      if(tab==='Voice')patch={voiceEnabled:data.has('voiceEnabled'),voiceName:data.get('voiceName')};
      if(tab==='Audio')for(const k of ['master','voice','interface','mechanical','ambience','music'])patch[k]=Number(data.get(k));
      if(tab==='Audio')patch.startup={...s.startup,enabled:data.has('startup-enabled'),seconds:Number(data.get('startup-seconds')),loopVideo:data.has('startup-loop')};
      if(tab==='Graphics')patch={quality:data.get('quality'),fps:Number(data.get('fps')),reduceOnBattery:data.has('reduceOnBattery')};
      if(tab==='Services'){patch={weather:{enabled:data.has('weather-enabled'),latitude:data.get('latitude')===''?null:Number(data.get('latitude')),longitude:data.get('longitude')===''?null:Number(data.get('longitude'))},ai:{enabled:data.has('ai-enabled'),endpoint:data.get('endpoint'),model:data.get('model')}};if(data.get('api-key'))await ctx.api('ai-key',data.get('api-key'));}
      await ctx.save(patch);form.querySelector('.save-status').textContent='Saved';
    });
  }
  function heard(){const el=this_el();if(!el)return;const rows=(ctx.status.commandHistory||[]).slice(0,6);el.innerHTML=rows.length?rows.map(r=>`<div class="heard ${r.accepted?(r.handled?'ok':'warn'):'low'}"><span>${new Date(r.time).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'})}</span><strong>${esc(r.text)}</strong><small>${r.confidence}% · ${r.accepted?(r.handled?'ACTED':'HEARD, NOT ACTED'):'TOO UNCLEAR'}</small></div>`).join(''):'<p class="muted">Nothing heard yet.</p>';}
  function this_el(){return el.querySelector('[data-heard]');}
  const offMeter=ctx.bridge.on('voice-meter',m=>{const bar=el.querySelector('[data-mic-bar]'),txt=el.querySelector('[data-mic-text]');if(!bar)return;bar.style.width=Math.max(2,Math.min(100,m.level))+'%';bar.classList.toggle('hot',m.level>35);txt.textContent=(m.detected?'Speech detected · ':'')+(m.level>0?`Level ${m.level}%`:'Silent')+(m.recognizer?` · ${m.recognizer}`:'');});
  const origDraw=draw;
  draw=async function(){await origDraw();heard();};
  draw().catch(e=>ctx.notify(e.message));return {update(){heard();},dispose(){offMeter();}};
}
