// ⚠ NOT LOADED AT RUNTIME. The settings UI that actually runs is the prebuilt
// renderer bundle in dist/assets/ (index-*.js). There is no build step that
// regenerates dist/ from this file, so edits here change NOTHING in the app.
// To change the settings UI you must patch dist/assets/index-*.js directly.
// Kept only as readable reference for the bundled code.
import {esc} from '../utils/dom.js';
const steps=['Discover displays','Identify screens','Assign roles','Test speakers','Test microphone','Choose graphics','Test wallpaper','Ready'];
export function mountWizard(el,ctx){let step=0;
  el.innerHTML=`<main class="wizard"><aside><div class="brand"><b>J</b><span>JARVIS<small>FIRST CONTACT</small></span></div><ol>${steps.map((s,i)=>`<li data-step="${i}"><span>${String(i+1).padStart(2,'0')}</span>${s}</li>`).join('')}</ol><p>Two screens.<br>One workspace.</p></aside><section><div class="wizard-page"></div><footer><button data-back>← Back</button><button class="primary" data-next>Continue →</button></footer></section></main>`;
  const page=el.querySelector('.wizard-page');
  async function draw(){el.querySelectorAll('[data-step]').forEach(li=>li.classList.toggle('active',Number(li.dataset.step)===step));el.querySelector('[data-back]').disabled=step===0;el.querySelector('[data-next]').textContent=step===7?'Launch JARVIS ↗':'Continue →';let body='';
    if(step===0){const b=await ctx.api('bootstrap');ctx.displays=b.displays;body=`<h1>A workspace<br>built around you.</h1><p class="muted">We found ${b.displays.length} display${b.displays.length===1?'':'s'}. Your resolution is detected automatically.</p><div class="display-cards">${b.displays.map(d=>`<div><strong>${d.number}</strong><span>${esc(d.label)}</span><small>${d.bounds.width} × ${d.bounds.height}</small></div>`).join('')}</div><p class="small muted">${b.displays.length===1?'One screen works too: the control deck opens inside your main display.':'Use Windows Extend mode so each screen can show its own workspace.'}</p>`;}
    if(step===1)body='<h1>Which screen<br>is which?</h1><p class="muted">Show a large number on each connected display for a few seconds.</p><button class="primary" data-test="identify">Identify my displays</button>';
    if(step===2){const opts=ctx.displays.map(d=>`<option value="${d.id}">${d.number} · ${esc(d.label)}</option>`).join('');body=`<h1>Give each screen<br>a purpose.</h1><label>Main cinematic display<select name="mainDisplay">${opts}</select></label><label>Control display<select name="controlDisplay"><option value="">Single screen</option>${opts}</select></label><button data-swap>Swap screens</button>`;}
    if(step===3)body='<h1>Sound,<br>with restraint.</h1><p class="muted">Test the spoken startup response and a subtle interface tone. Use your normal Windows speakers or headphones.</p><button class="primary" data-test="audio-test">Test speakers</button><p class="small muted">The system continues if speech or audio is unavailable.</p>';
    if(step===4)body=`<h1>At your<br>command.</h1><p class="voice-phrase">“Jarvis, let's get to work.”</p><p class="muted">Voice listening is optional and starts only when you enable it. Ctrl + Alt + J and the system tray always provide alternatives.</p><button class="primary" data-test="microphone-test">Enable & test microphone</button><button data-mic-off>Keep microphone off</button><div class="status-box" data-voice-state>${esc(ctx.status.voice)}</div>`;
    if(step===5)body='<h1>Find your<br>balance.</h1><p class="muted">Start with Auto. On battery, JARVIS reduces the frame rate, reflections and effects.</p><label>Graphics quality<select name="quality"><option value="auto">Auto</option><option value="low">Low · longest battery life</option><option value="medium">Medium</option><option value="high">High</option><option value="ultra">Ultra</option></select></label><label class="check"><input name="reduceOnBattery" type="checkbox" checked>Reduce graphics on battery</label>';
    if(step===6)body=`<h1>A quiet presence<br>on your desktop.</h1><p class="muted">Test the animated wallpaper behind your normal icons. Setup will hide for a few seconds, then return.</p><button class="primary" data-test="wallpaper-test">Test wallpaper</button><div class="status-box" data-wallpaper-state>${esc(ctx.status.wallpaper)}</div><p class="small muted">If this Windows build does not support the desktop attachment, the supplied Lively package is the fallback.</p>`;
    if(step===7)body='<h1>Ready when<br>you are.</h1><p class="muted">Your first startup reveals the Hall of Armor from inside the helmet.</p><div class="shortcut-summary"><span>START</span><b>Ctrl + Alt + J</b><span>ARMOR HALL</span><b>Ctrl + Alt + H</b><span>STAND DOWN</span><b>Ctrl + Alt + X</b><span>BACK</span><b>Esc</b></div><p class="small muted">Revisit display, voice and graphics choices in Settings.</p>';
    page.innerHTML=`<p class="eyebrow">SETUP / ${String(step+1).padStart(2,'0')}</p>${body}`;
    if(step===2){page.querySelector('[name=mainDisplay]').value=String(ctx.settings.mainDisplay??ctx.displays[0]?.id);page.querySelector('[name=controlDisplay]').value=String(ctx.settings.controlDisplay??ctx.displays[1]?.id??'');page.querySelector('[data-swap]').onclick=()=>{const a=page.querySelector('[name=mainDisplay]'),b=page.querySelector('[name=controlDisplay]');if(b.value){const value=a.value;a.value=b.value;b.value=value;}};}
    page.querySelectorAll('[data-test]').forEach(b=>b.onclick=async()=>{try{const result=await ctx.api(b.dataset.test);if(typeof result==='string')ctx.notify(result);else if(b.dataset.test==='microphone-test')ctx.notify('Say the activation phrase. Status will update below.');}catch(e){ctx.notify(e.message);}});page.querySelector('[data-mic-off]')?.addEventListener('click',()=>ctx.save({voiceEnabled:false}));
  }
  el.querySelector('[data-back]').onclick=()=>{if(step>0){step--;draw();}};
  el.querySelector('[data-next]').onclick=async()=>{try{if(step===2){const main=Number(page.querySelector('[name=mainDisplay]').value),control=page.querySelector('[name=controlDisplay]').value;if(control&&Number(control)===main)throw Error('Choose two different displays, or select Single screen.');await ctx.save({mainDisplay:main,controlDisplay:control?Number(control):null,singleScreen:!control&&(ctx.displays||[]).length>1});}if(step===5)await ctx.save({quality:page.querySelector('[name=quality]').value,reduceOnBattery:page.querySelector('[name=reduceOnBattery]').checked});if(step===7){await ctx.api('setup-complete',{});return;}step++;await draw();}catch(e){ctx.notify(e.message);}};
  draw().catch(e=>ctx.notify(e.message));return {update(){if(page.querySelector('[data-voice-state]'))page.querySelector('[data-voice-state]').textContent=ctx.status.voice;if(page.querySelector('[data-wallpaper-state]'))page.querySelector('[data-wallpaper-state]').textContent=ctx.status.wallpaper;},dispose(){}};
}
