// ⚠ NOT LOADED AT RUNTIME. The settings UI that actually runs is the prebuilt
// renderer bundle in dist/assets/ (index-*.js). There is no build step that
// regenerates dist/ from this file, so edits here change NOTHING in the app.
// To change the settings UI you must patch dist/assets/index-*.js directly.
// Kept only as readable reference for the bundled code.
import {esc} from '../utils/dom.js';
/** Settings editor for themes and suits. Saves per suit through the `suit-save` API. */
export function mountWorkstationSettings(area,ctx){
  let data=null,themeId=null,suitId=null,draft=null;
  async function load(){data=await ctx.api('workstations');themeId=themeId&&data.themes.some(t=>t.id===themeId)?themeId:data.activeTheme;const list=data.allSuits[themeId];suitId=list.some(s=>s.id===suitId)?suitId:list[0].id;draft=structuredClone(list.find(s=>s.id===suitId));draw();}
  function draw(){
    const theme=data.themes.find(t=>t.id===themeId),suits=data.allSuits[themeId];
    const L=draft.layout&&Array.isArray(draft.layout.windows)?draft.layout:{enabled:true,windows:[]};draft.layout=L;
    area.innerHTML=`<div class="settings-heading"><p class="eyebrow">PREFERENCES / WORKSTATIONS</p><h1>Suits.</h1></div><p class="muted">Every suit is a workstation: a name, a folder for its files, the links and apps to open when you activate it. Voice: “${esc(theme.assistant)}, open ${esc(draft.name)}”.</p>
    <div class="ws-settings-themes">${data.themes.map(t=>`<button type="button" class="theme-chip ${t.id===themeId?'active':''}" data-pick-theme="${t.id}" style="--chip:${t.accent}"><i></i>${esc(t.name)}<small>${esc(t.assistant)} · ${esc(t.purpose)}</small></button>`).join('')}<button type="button" data-activate-theme ${themeId===data.activeTheme?'disabled':''}>${themeId===data.activeTheme?'This hall is active':'Switch to this hall now'}</button></div>
    <div class="card ws-media-card"><p class="eyebrow">HALL TRANSITION · ${esc(theme.name.toUpperCase())}</p><p class="small muted">Optional. Each hall already has a built-in switch effect (armor streak, bats, webs). Add a clip here to replace it; use a green-screen clip and keep the tick on so only the bats/effect shows over the hall.</p><div class="ws-folder-row"><code>${esc(theme.media?.transitionVideo?theme.media.transitionVideo.split('/').pop():'No transition video')}</code><button type="button" data-media-video>Choose video</button><button type="button" data-media-video-clear>Remove</button></div><div class="ws-folder-row"><code>${esc(theme.media?.transitionSound?theme.media.transitionSound.split('/').pop():'No sound (video is muted)')}</code><button type="button" data-media-sound>Choose sound</button><button type="button" data-media-sound-clear>Remove</button></div><label class="check"><input type="checkbox" data-media-chroma ${theme.media?.chromaKey!==false?'checked':''}>Remove green background (green-screen clip)</label><h4>Lead-in clip (optional)</h4><p class="small muted">Plays first — e.g. a flashbang. At the flash time the screen goes black so only the case drop and suit show until the hall is revealed.</p><div class="ws-folder-row"><code>${esc(theme.media?.preVideo?theme.media.preVideo.split('/').pop():'No lead-in clip')}</code><button type="button" data-media-pre>Choose clip</button><button type="button" data-media-pre-clear>Remove</button></div><div class="two-col"><label>Black out at (seconds into lead-in)<input type="number" min="0" step="0.1" data-media-flash value="${theme.media?.preFlashAt||0}"></label><label class="check"><input type="checkbox" data-media-blackout ${theme.media?.blackout?'checked':''}>Black out the hall until the transition ends</label></div><div class="two-col"><label>Start at (seconds)<input type="number" min="0" step="0.5" data-media-start value="${theme.media?.start||0}"></label><label>Stop at (seconds, 0 = end of clip)<input type="number" min="0" step="0.5" data-media-end value="${theme.media?.end||0}"></label></div><p class="small muted">Example: start 10, stop 16 plays just that six-second section. Longest playback is 15 seconds.</p></div>
    <div class="ws-settings-grid"><nav class="ws-settings-list">${suits.map(s=>`<button type="button" class="${s.id===suitId?'active':''}" data-pick-suit="${s.id}" style="--suit:${s.accent}"><span>${String(suits.indexOf(s)+1).padStart(2,'0')}</span><b>${esc(s.name)}</b><small>${s.folder?esc(s.folder.split(/[\\/]/).pop()):'no folder'} · ${s.links.length} links · ${s.apps.length} apps</small></button>`).join('')}</nav>
    <form class="ws-settings-form card"><label>Suit name<input name="name" value="${esc(draft.name)}" maxlength="40" required></label><label>Subtitle (shown on the hall and control deck)<input name="subtitle" value="${esc(draft.subtitle)}" maxlength="80" placeholder="e.g. EfficiencAI · JobAdder integration"></label><label>Accent<input name="accent" type="color" value="${esc(draft.accent)}"></label>
    <h3>Files</h3><div class="ws-folder-row"><code data-folder>${esc(draft.folder||'No folder yet')}</code><button type="button" data-choose-folder>Choose folder</button><button type="button" data-auto-folder>Create in Documents</button>${draft.folder?'<button type="button" data-clear-folder>Clear</button>':''}</div><p class="small muted">The folder shows on your lower display whenever this suit is active. Drop files onto it from Explorer.</p>
    <h3>Links</h3><div data-links>${draft.links.map((l,i)=>`<div class="ws-row"><input value="${esc(l.label)}" data-link-label="${i}" maxlength="60" placeholder="Label"><input value="${esc(l.url)}" data-link-url="${i}" placeholder="https://…" required><select data-link-target="${i}"><option value="browser" ${l.target==='browser'?'selected':''}>Default browser</option><option value="inapp" ${l.target==='inapp'?'selected':''}>Tab inside ${esc(theme.assistant)}</option></select><button type="button" data-link-remove="${i}">×</button></div>`).join('')}</div><button type="button" data-link-add>+ Add link</button>
    <h3>Apps</h3><div data-apps>${draft.apps.map((a,i)=>`<div class="ws-row"><input value="${esc(a.label)}" data-app-label="${i}" maxlength="60" placeholder="Label"><code>${esc(a.path)}</code><button type="button" data-app-remove="${i}">×</button></div>`).join('')}</div><button type="button" data-app-add>+ Add app or shortcut</button>
    <h3>Screens</h3><p class="small muted">When this suit opens, these windows are moved onto the screen you pick. <b>Top screen</b> is the one above the keyboard; <b>bottom screen</b> is the second panel underneath. Match on part of the window title (“Claude”) or on the app name (“chrome”).</p>
    <div data-layout>${L.windows.map((w,i)=>`<div class="ws-row"><input value="${esc(w.match)}" data-lay-match="${i}" maxlength="80" placeholder="Window title or app name"><select data-lay-by="${i}"><option value="title" ${w.matchBy==='title'?'selected':''}>Title contains</option><option value="process" ${w.matchBy==='process'?'selected':''}>App name</option></select><select data-lay-display="${i}"><option value="top" ${w.display==='top'?'selected':''}>Top screen</option><option value="bottom" ${w.display==='bottom'?'selected':''}>Bottom screen</option></select><select data-lay-area="${i}"><option value="full" ${w.area==='full'?'selected':''}>Whole screen</option><option value="left" ${w.area==='left'?'selected':''}>Left half</option><option value="right" ${w.area==='right'?'selected':''}>Right half</option><option value="top" ${w.area==='top'?'selected':''}>Top half</option><option value="bottom" ${w.area==='bottom'?'selected':''}>Bottom half</option></select><button type="button" data-lay-app="${i}" data-path="${esc(w.launch||'')}" title="${esc(w.launch||'Start this app if it is not already open')}">${w.launch?esc(w.launch.split(/[\\/]/).pop()):'Start if closed…'}</button><button type="button" data-lay-remove="${i}">×</button></div>`).join('')}</div>
    <div class="ws-folder-row"><button type="button" data-lay-add>+ Add window</button><button type="button" data-lay-pick>Pick from open windows</button><button type="button" data-lay-test>Arrange now</button></div><div data-lay-picker></div>
    <label class="check"><input type="checkbox" name="layoutEnabled" ${L.enabled?'checked':''}>Arrange these windows automatically when the suit activates</label>
    <label class="check"><input type="checkbox" name="autoLaunch" ${draft.autoLaunch?'checked':''}>Open links and apps automatically when the suit activates</label>
    <footer><button class="primary" type="submit">Save suit</button><span class="save-status"></span></footer></form></div>`;
    area.querySelectorAll('[data-pick-theme]').forEach(b=>b.onclick=()=>{themeId=b.dataset.pickTheme;suitId=null;load();});
    area.querySelector('[data-activate-theme]').onclick=async()=>{try{await ctx.api('theme-set',themeId);await load();}catch(e){ctx.notify(e.message);}};
    const mediaSave=patch=>ctx.api('theme-media-save',{theme:themeId,patch}).then(()=>load()).catch(e=>ctx.notify(e.message));
    for(const [sel,type,key]of [['[data-media-video]','transition-video','transitionVideo'],['[data-media-sound]','transition-sound','transitionSound']]){area.querySelector(sel).onclick=async()=>{try{const url=await ctx.api('choose',{type});if(typeof url==='string')await mediaSave({[key]:url});}catch(e){ctx.notify(e.message);}};area.querySelector(sel.replace(']','-clear]')).onclick=()=>mediaSave({[key]:''});}
    area.querySelector('[data-media-chroma]').onchange=e=>mediaSave({chromaKey:e.target.checked});
    area.querySelector('[data-media-pre]').onclick=async()=>{try{const url=await ctx.api('choose',{type:'transition-video'});if(typeof url==='string')await mediaSave({preVideo:url});}catch(e){ctx.notify(e.message);}};area.querySelector('[data-media-pre-clear]').onclick=()=>mediaSave({preVideo:'',preSound:''});area.querySelector('[data-media-flash]').onchange=e=>mediaSave({preFlashAt:Number(e.target.value)});area.querySelector('[data-media-blackout]').onchange=e=>mediaSave({blackout:e.target.checked});
    area.querySelector('[data-media-start]').onchange=e=>mediaSave({start:Number(e.target.value)});area.querySelector('[data-media-end]').onchange=e=>mediaSave({end:Number(e.target.value)});
    area.querySelectorAll('[data-pick-suit]').forEach(b=>b.onclick=()=>{suitId=b.dataset.pickSuit;draft=structuredClone(suits.find(s=>s.id===suitId));draw();});
    const form=area.querySelector('form');
    const sync=()=>{draft.name=form.elements.name.value;draft.subtitle=form.elements.subtitle.value;draft.accent=form.elements.accent.value;draft.autoLaunch=form.elements.autoLaunch.checked;draft.links=draft.links.map((l,i)=>({label:form.querySelector(`[data-link-label="${i}"]`).value,url:form.querySelector(`[data-link-url="${i}"]`).value,target:form.querySelector(`[data-link-target="${i}"]`).value}));draft.apps=draft.apps.map((a,i)=>({...a,label:form.querySelector(`[data-app-label="${i}"]`).value}));draft.layout={enabled:form.elements.layoutEnabled.checked,windows:[...form.querySelectorAll('[data-lay-match]')].map(el=>{const i=el.dataset.layMatch;return {match:el.value,matchBy:form.querySelector(`[data-lay-by="${i}"]`).value,display:form.querySelector(`[data-lay-display="${i}"]`).value,area:form.querySelector(`[data-lay-area="${i}"]`).value,launch:form.querySelector(`[data-lay-app="${i}"]`).dataset.path||''};})};};
    form.querySelector('[data-choose-folder]').onclick=async()=>{try{const f=await ctx.api('suit-choose-folder');if(f){sync();draft.folder=f;draw();}}catch(e){ctx.notify(e.message);}};
    form.querySelector('[data-auto-folder]').onclick=async()=>{try{sync();await save();const f=await ctx.api('folder-create',draft.id);ctx.notify('Folder created: '+f);await load();}catch(e){ctx.notify(e.message);}};
    form.querySelector('[data-clear-folder]')?.addEventListener('click',()=>{sync();draft.folder='';draw();});
    form.querySelector('[data-link-add]').onclick=()=>{sync();draft.links.push({label:'',url:'',target:'browser'});draw();form.querySelector(`[data-link-url="${draft.links.length-1}"]`)?.focus();};
    form.querySelectorAll('[data-link-remove]').forEach(b=>b.onclick=()=>{sync();draft.links.splice(+b.dataset.linkRemove,1);draw();});
    form.querySelector('[data-app-add]').onclick=async()=>{try{const p=await ctx.api('suit-choose-app');if(p){sync();draft.apps.push({label:p.split(/[\\/]/).pop().replace(/\.(exe|lnk|bat|cmd|url)$/i,''),path:p});draw();}}catch(e){ctx.notify(e.message);}};
    form.querySelectorAll('[data-app-remove]').forEach(b=>b.onclick=()=>{sync();draft.apps.splice(+b.dataset.appRemove,1);draw();});
    form.querySelector('[data-lay-add]').onclick=()=>{sync();draft.layout.windows.push({match:'',matchBy:'title',display:'top',area:'full',launch:''});draw();form.querySelector(`[data-lay-match="${draft.layout.windows.length-1}"]`)?.focus();};
    form.querySelectorAll('[data-lay-remove]').forEach(b=>b.onclick=()=>{sync();draft.layout.windows.splice(+b.dataset.layRemove,1);draw();});
    form.querySelectorAll('[data-lay-app]').forEach(b=>b.onclick=async()=>{try{const path=await ctx.api('suit-choose-app');if(path){sync();draft.layout.windows[+b.dataset.layApp].launch=path;draw();}}catch(e){ctx.notify(e.message);}});
    form.querySelector('[data-lay-pick]').onclick=async()=>{
      const host=form.querySelector('[data-lay-picker]');host.textContent='Reading open windows…';
      try{const res=await ctx.api('layout-windows');
        if(res.error){host.textContent=res.error;return;}
        if(!res.windows.length){host.textContent='No open windows found.';return;}
        host.innerHTML=`<select data-lay-choice><option value="">Choose an open window…</option>${res.windows.map((w,i)=>`<option value="${i}">${esc(w.process)} — ${esc(w.title)}</option>`).join('')}</select>`;
        host.querySelector('[data-lay-choice]').onchange=e=>{const w=res.windows[+e.target.value];if(!w)return;sync();draft.layout.windows.push({match:w.title.slice(0,80),matchBy:'title',display:'top',area:'full',launch:''});draw();};
      }catch(e){host.textContent=e.message;}
    };
    form.querySelector('[data-lay-test]').onclick=async()=>{
      try{await save();const r=await ctx.api('layout-apply',{id:draft.id});
        if(r.error)ctx.notify(r.error);
        else ctx.notify(r.missing?.length?`Placed ${r.placed}. Not open: ${r.missing.join(', ')}`:`Placed ${r.placed} window${r.placed===1?'':'s'}.`);
      }catch(e){ctx.notify(e.message);}
    };
    async function save(){sync();const links=draft.links.filter(l=>l.url.trim()).map(l=>({...l,label:l.label.trim()||l.url.replace(/^https?:\/\//,'').split('/')[0]}));const patch={name:draft.name,subtitle:draft.subtitle,accent:draft.accent,folder:draft.folder,links,apps:draft.apps,autoLaunch:draft.autoLaunch,layout:{enabled:draft.layout.enabled,windows:draft.layout.windows.filter(w=>String(w.match||'').trim())}};data=await ctx.api('suit-save',{id:draft.id,theme:themeId,patch});}
    form.onsubmit=async e=>{e.preventDefault();try{await save();form.querySelector('.save-status').textContent='Saved';await load();}catch(err){ctx.notify(err.message);}};
  }
  load().catch(e=>ctx.notify(e.message));
  return {refresh:load};
}
